name: test_scanner
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0


environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  qrscan: ^0.3.3
  flutter:
    sdk: flutter
  permission_handler: ^11.0.1
  material: ^1.0.0+2
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.1.14
  url_launcher_android: ^6.1.0
  firebase_core: ^2.17.0
  cloud_firestore: ^4.9.3
  flutter_tts: ^3.8.3
  translator: ^0.1.7
  easy_localization: ^3.0.3
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/icons/
    - lib/images/

  fonts:
    - family: NexaTextDemo-Bold
      fonts:
        - asset: assets/fonts/NexaTextDemo-Bold.ttf
        
    - family: Nexa-Trial-Regular
      fonts:
        - asset: assets/fonts/Nexa-Trial-Regular.ttf
        